### ISSUE TITLE
Anyway to turn off the $ for end of line?

### ISSUE THREAD

**Issue by chookity-pokk** [fgeller/leerzeichen.el#4]
Thank you for the package, I really like it though I would prefer not having a $ at the end of each line. I was wondering if there is a way to toggle this on/off?

**Comment by fgeller** [comment]
glad it helps!
this would stop highlighting the end of a new line:
```
(setq leerzeichen-line-feed-glyph nil)
```
please re-open or comment here if you have further questions!
